export const USER_LOADING = 'USER_LOADING';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_UPDATE_INFO = 'USER_UPDATE_INFO';

export const CATEGORY_LOADING_ALL = 'CATEGORY_LOADING_ALL';

export const CAKE_LOADING_ALL = 'CAKE_LOADING_ALL';

export const CART_LOADING_ALL = 'CART_LOADING_ALL';
export const CART_CLEAR = 'CART_CLEAR';
export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REDUCE_ITEM = 'CART_REDUCE_ITEM';
export const CART_DELETE_ITEM = 'CART_DELETE_ITEM';

export const ORDER_LOADING = 'ORDER_LOADING';

/* ADMIN ONLY */
export const USER_LOADING_ALL = 'USER_LOADING_ALL';
export const USER_DELETE = 'USER_DELETE';

export const ORDER_LOADING_ALL = 'ORDER_LOADING_ALL';
export const ORDER_STATUS_UPDATE = 'ORDER_STATUS_UPDATE';
